spring:
  application:
    name: book
  datasource:
      url: jdbc:mysql://101.132.147.85:50520/smartirrigation_schedule?serverTimezone=UTC
      username: root
      password: 40FH8s2jR@6
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

server:
  port: 9093
mybatis:
  mapper-locations: classpath:com/liys/book/mapper/*.xml