spring:
  application:
    name: smartirrigation-system
  datasource:
    url: jdbc:mysql://101.132.147.85:50520/smartirrigation_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 40FH8s2jR@6
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://qhzssy:qhzssy@localhost:8073/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:cn/qhzssy/smartirrigate/mapper/*.xml
ribbon: 
  eureka: 
    enabled: false
feign:
  hystrix:
    enabled: false  
one:
  ribbon:
    listOfServers: http://localhost:8072
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  maxAutoRetries: 0